on: push
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: "读取仓库内容"
        run: actions/checkout@v4
      - name: "安装依赖"
        run: npm install
      - name: "build工程"
        run: npm run build
   
